CREATE TABLE "kvelpo_application" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kvelpo_application_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerkUserId" varchar(256) NOT NULL,
	"projectRoleNeededId" integer NOT NULL,
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"message" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "kvelpo_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kvelpo_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"projectId" integer NOT NULL,
	"clerkUserId" varchar(256) NOT NULL,
	"message" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "kvelpo_notification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kvelpo_notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerkUserId" varchar(256) NOT NULL,
	"projectId" integer,
	"type" varchar(100) NOT NULL,
	"message" text NOT NULL,
	"isRead" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "kvelpo_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kvelpo_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerkUserId" varchar(256) NOT NULL,
	"fullName" varchar(256),
	"bio" text,
	"avatarUrl" varchar(512),
	"isPublic" boolean DEFAULT true NOT NULL,
	"link1" varchar(512),
	"link2" varchar(512),
	"link3" varchar(512),
	"membership" varchar(16) DEFAULT 'free' NOT NULL,
	"jsonb" json DEFAULT '[]'::json NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "kvelpo_profile_clerkUserId_unique" UNIQUE("clerkUserId")
);
--> statement-breakpoint
CREATE TABLE "kvelpo_project_member" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kvelpo_project_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"projectId" integer NOT NULL,
	"clerkUserId" varchar(256) NOT NULL,
	"role" varchar(50) DEFAULT 'member' NOT NULL,
	"joinedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "kvelpo_project_role_needed" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kvelpo_project_role_needed_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"projectId" integer NOT NULL,
	"title" varchar(256) NOT NULL,
	"description" text,
	"slotsNeeded" integer DEFAULT 1 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "kvelpo_project" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kvelpo_project_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerkUserId" varchar(256) NOT NULL,
	"name" varchar(256) NOT NULL,
	"description" text,
	"isPublic" boolean DEFAULT true NOT NULL,
	"jsonb" json DEFAULT '[]'::json NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "kvelpo_application" ADD CONSTRAINT "kvelpo_application_projectRoleNeededId_kvelpo_project_role_needed_id_fk" FOREIGN KEY ("projectRoleNeededId") REFERENCES "public"."kvelpo_project_role_needed"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kvelpo_message" ADD CONSTRAINT "kvelpo_message_projectId_kvelpo_project_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."kvelpo_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kvelpo_notification" ADD CONSTRAINT "kvelpo_notification_projectId_kvelpo_project_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."kvelpo_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kvelpo_project_member" ADD CONSTRAINT "kvelpo_project_member_projectId_kvelpo_project_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."kvelpo_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kvelpo_project_role_needed" ADD CONSTRAINT "kvelpo_project_role_needed_projectId_kvelpo_project_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."kvelpo_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "applications_clerk_user_id_idx" ON "kvelpo_application" USING btree ("clerkUserId");--> statement-breakpoint
CREATE INDEX "project_role_needed_id_idx" ON "kvelpo_application" USING btree ("projectRoleNeededId");--> statement-breakpoint
CREATE INDEX "status_idx" ON "kvelpo_application" USING btree ("status");--> statement-breakpoint
CREATE INDEX "messages_project_id_idx" ON "kvelpo_message" USING btree ("projectId");--> statement-breakpoint
CREATE INDEX "messages_clerk_user_id_idx" ON "kvelpo_message" USING btree ("clerkUserId");--> statement-breakpoint
CREATE INDEX "messages_created_at_idx" ON "kvelpo_message" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "notifications_clerk_user_id_idx" ON "kvelpo_notification" USING btree ("clerkUserId");--> statement-breakpoint
CREATE INDEX "is_read_idx" ON "kvelpo_notification" USING btree ("isRead");--> statement-breakpoint
CREATE INDEX "profile_clerk_user_id_idx" ON "kvelpo_profile" USING btree ("clerkUserId");--> statement-breakpoint
CREATE INDEX "is_public_idx" ON "kvelpo_profile" USING btree ("isPublic");--> statement-breakpoint
CREATE INDEX "project_members_project_id_idx" ON "kvelpo_project_member" USING btree ("projectId");--> statement-breakpoint
CREATE INDEX "project_members_clerk_user_id_idx" ON "kvelpo_project_member" USING btree ("clerkUserId");--> statement-breakpoint
CREATE INDEX "project_roles_needed_project_id_idx" ON "kvelpo_project_role_needed" USING btree ("projectId");--> statement-breakpoint
CREATE INDEX "projects_clerk_user_id_idx" ON "kvelpo_project" USING btree ("clerkUserId");--> statement-breakpoint
CREATE INDEX "name_idx" ON "kvelpo_project" USING btree ("name");--> statement-breakpoint
CREATE INDEX "projects_is_public_idx" ON "kvelpo_project" USING btree ("isPublic");