CREATE TABLE "kvelpo_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kvelpo_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"projectId" integer NOT NULL,
	"clerkUserId" varchar(256) NOT NULL,
	"message" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "wegotit_application" RENAME TO "kvelpo_application";--> statement-breakpoint
ALTER TABLE "wegotit_notification" RENAME TO "kvelpo_notification";--> statement-breakpoint
ALTER TABLE "wegotit_profile" RENAME TO "kvelpo_profile";--> statement-breakpoint
ALTER TABLE "wegotit_project_member" RENAME TO "kvelpo_project_member";--> statement-breakpoint
ALTER TABLE "wegotit_project_role_needed" RENAME TO "kvelpo_project_role_needed";--> statement-breakpoint
ALTER TABLE "wegotit_project" RENAME TO "kvelpo_project";--> statement-breakpoint
ALTER TABLE "kvelpo_profile" DROP CONSTRAINT "wegotit_profile_clerkUserId_unique";--> statement-breakpoint
ALTER TABLE "kvelpo_application" DROP CONSTRAINT "wegotit_application_projectRoleNeededId_wegotit_project_role_needed_id_fk";
--> statement-breakpoint
ALTER TABLE "kvelpo_notification" DROP CONSTRAINT "wegotit_notification_projectId_wegotit_project_id_fk";
--> statement-breakpoint
ALTER TABLE "kvelpo_project_member" DROP CONSTRAINT "wegotit_project_member_projectId_wegotit_project_id_fk";
--> statement-breakpoint
ALTER TABLE "kvelpo_project_role_needed" DROP CONSTRAINT "wegotit_project_role_needed_projectId_wegotit_project_id_fk";
--> statement-breakpoint
ALTER TABLE "kvelpo_profile" ADD COLUMN "jsonb" json DEFAULT '[]'::json NOT NULL;--> statement-breakpoint
ALTER TABLE "kvelpo_project" ADD COLUMN "jsonb" json DEFAULT '[]'::json NOT NULL;--> statement-breakpoint
ALTER TABLE "kvelpo_message" ADD CONSTRAINT "kvelpo_message_projectId_kvelpo_project_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."kvelpo_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "messages_project_id_idx" ON "kvelpo_message" USING btree ("projectId");--> statement-breakpoint
CREATE INDEX "messages_clerk_user_id_idx" ON "kvelpo_message" USING btree ("clerkUserId");--> statement-breakpoint
CREATE INDEX "messages_created_at_idx" ON "kvelpo_message" USING btree ("createdAt");--> statement-breakpoint
ALTER TABLE "kvelpo_application" ADD CONSTRAINT "kvelpo_application_projectRoleNeededId_kvelpo_project_role_needed_id_fk" FOREIGN KEY ("projectRoleNeededId") REFERENCES "public"."kvelpo_project_role_needed"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kvelpo_notification" ADD CONSTRAINT "kvelpo_notification_projectId_kvelpo_project_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."kvelpo_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kvelpo_project_member" ADD CONSTRAINT "kvelpo_project_member_projectId_kvelpo_project_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."kvelpo_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kvelpo_project_role_needed" ADD CONSTRAINT "kvelpo_project_role_needed_projectId_kvelpo_project_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."kvelpo_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kvelpo_profile" ADD CONSTRAINT "kvelpo_profile_clerkUserId_unique" UNIQUE("clerkUserId");