CREATE TABLE IF NOT EXISTS "kvelpo_experience" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kvelpo_experience_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerkUserId" varchar(256) NOT NULL,
	"title" varchar(256) NOT NULL,
	"organization" varchar(256) NOT NULL,
	"location" varchar(256),
	"startDate" date NOT NULL,
	"endDate" date,
	"description" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "experiences_clerk_user_id_idx" ON "kvelpo_experience" USING btree ("clerkUserId");
