CREATE TABLE IF NOT EXISTS "kvelpo_report" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kvelpo_report_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"reporterClerkUserId" varchar(256) NOT NULL,
	"targetType" varchar(16) NOT NULL,
	"targetId" varchar(256) NOT NULL,
	"reason" varchar(32) NOT NULL,
	"details" text,
	"status" varchar(16) DEFAULT 'open' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"resolvedAt" timestamp with time zone,
	"resolvedBy" varchar(256)
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reports_status_idx" ON "kvelpo_report" USING btree ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reports_reporter_idx" ON "kvelpo_report" USING btree ("reporterClerkUserId");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reports_target_idx" ON "kvelpo_report" USING btree ("targetType","targetId");
