ALTER TABLE "kvelpo_profile" ADD COLUMN IF NOT EXISTS "bannedAt" timestamp with time zone;
--> statement-breakpoint
ALTER TABLE "kvelpo_profile" ADD COLUMN IF NOT EXISTS "bannedReason" text;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "kvelpo_moderation_action" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kvelpo_moderation_action_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"adminClerkUserId" varchar(256) NOT NULL,
	"action" varchar(16) NOT NULL,
	"targetClerkUserId" varchar(256),
	"projectId" integer,
	"projectName" varchar(256),
	"reason" text,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "moderation_actions_created_at_idx" ON "kvelpo_moderation_action" USING btree ("createdAt");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "moderation_actions_target_idx" ON "kvelpo_moderation_action" USING btree ("targetClerkUserId");
